#!/bin/bash
APP="$1"; IMAGE="dokku/$APP"

set -e

# Check for Procfile
ID=$(docker run -d $IMAGE test -f app/Procfile)
if [ $(docker wait $ID) -ne 0 ]; then
  exit 0
fi

echo "-----> Injecting GraphicsMagick ..."

CMD="cat > gm && \
  dpkg -s graphicsmagick > /dev/null 2>&1 || \
  (apt-get update && apt-get install -y graphicsmagick && apt-get clean)"

ID=$(echo "$runner" | docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
